### PR TITLE
Update break_time.py

### PR DESCRIPTION
**Pull request by AdityaNaresh**
these are some improvements.
In the collection Section, we can also include a function which will help the user to make his own personal collection.

### CODE REVIEW

**Comment by supercontracts** [comment]
ask for the sleep time in some specific unit cause time.sleep() takes input in seconds so you got to convert your input accordingly

**Comment by AdityaNaresh** [comment]
there is no option to edit current commit so merge this I'll do that in another commit

**Comment by supercontracts** [comment]
you can edit it

**Comment by supercontracts** [comment]
click on your merge request and there is a edit pencil shown on the top. edit your code and commit again

**Comment by AdityaNaresh** [comment]
I have deleted the clone repo's patch 3
so there is no repo to commit to

**Comment by supercontracts** [comment]
okkay i will merge this request

**Comment by supercontracts** [comment]
This issue maybe closed for now.. After this we will add more options other than videos

**Comment by AdityaNaresh** [comment]
Yup

**Pull request merged**
